import { NativeModules, Platform } from "react-native";

import type { Timer } from "@/types";

/**
 * Bridge for the App Group (iOS) / SharedPreferences (Android) data that the
 * widget extensions read.
 *
 * The native side of this bridge is generated by `plugins/withQaharWidget.js`.
 * If the native module isn't present (e.g. running in Expo Go), every method
 * is a quiet no-op — the in-app experience still works fine.
 */
type Bridge = {
  setTimers: (json: string) => Promise<void>;
  setWidgetTimerId: (id: string | null) => Promise<void>;
};

const native = (NativeModules as { QaharWidgetBridge?: Bridge })
  .QaharWidgetBridge;

const SHARED_KEY_TIMERS = "qahar.timers";
const SHARED_KEY_WIDGET_ID = "qahar.widgetTimerId";

export async function syncTimersToWidget(timers: Timer[]): Promise<void> {
  if (!native) return;
  // Only ship the fields the widget needs. Keeps the cross-process payload small.
  const compact = timers
    .filter((t) => !t.archived)
    .map((t) => ({
      id: t.id,
      label: t.label,
      startedAt: t.startedAt,
      pausedAt: t.pausedAt,
      accumulatedPause: t.accumulatedPause,
      color: t.color,
    }));
  try {
    await native.setTimers(JSON.stringify(compact));
  } catch (err) {
    console.warn("[shared-storage] setTimers failed", err);
  }
}

export async function syncWidgetTimerId(id: string | null): Promise<void> {
  if (!native) return;
  try {
    await native.setWidgetTimerId(id);
  } catch (err) {
    console.warn("[shared-storage] setWidgetTimerId failed", err);
  }
}

/** Exposed for debugging/tests — not used in app code. */
export const SHARED_KEYS = {
  timers: SHARED_KEY_TIMERS,
  widgetTimerId: SHARED_KEY_WIDGET_ID,
  platform: Platform.OS,
} as const;
